# This file was generated automatically
# Contains the CLEANED list of effects, based on filters
# (Primary Threshold: 30.0%, Fallback: Max Count)

MOVE_EFFECTS_DETAILED = { 'agility': ['user_boost'],
  'amnesia': ['user_boost'],
  'blizzard': ['damage', 'opponent_status'],
  'bodyslam': ['damage', 'opponent_status'],
  'clamp': ['damage'],
  'confuseray': ['user_boost'],
  'counter': ['damage'],
  'doubleedge': ['damage'],
  'doublekick': ['damage'],
  'drillpeck': ['damage'],
  'earthquake': ['damage'],
  'explosion': ['damage'],
  'fireblast': ['damage', 'opponent_status'],
  'firespin': ['damage'],
  'hyperbeam': ['damage'],
  'hypnosis': ['opponent_status'],
  'icebeam': ['damage', 'opponent_status'],
  'lovelykiss': ['opponent_status'],
  'megadrain': ['damage', 'healing'],
  'nightshade': ['damage'],
  'psychic': ['damage', 'opponent_debuff'],
  'razorleaf': ['damage'],
  'recover': ['healing'],
  'reflect': ['user_boost'],
  'rest': ['healing', 'user_status'],
  'rockslide': ['damage'],
  'seismictoss': ['damage'],
  'selfdestruct': ['damage'],
  'sing': ['opponent_status'],
  'slash': ['damage'],
  'sleeppowder': ['opponent_status'],
  'softboiled': ['healing'],
  'stunspore': ['opponent_status'],
  'substitute': ['user_boost'],
  'surf': ['damage'],
  'swordsdance': ['user_boost'],
  'thunderbolt': ['damage', 'opponent_status'],
  'thunderwave': ['opponent_status'],
  'toxic': ['opponent_status'],
  'wrap': ['damage']}
