# Questo file è stato generato automaticamente
# Contiene i CONTEGGI GREZZI di usi/effetti per ogni mossa.

MOVE_STATS_RAW = { 'agility': {'effects': {'damage': 22, 'user_boost': 1162}, 'total_uses': 1388},
  'amnesia': {'effects': {'damage': 204, 'opponent_status': 2, 'user_boost': 4526}, 'total_uses': 6315},
  'blizzard': { 'effects': {'damage': 12117, 'opponent_debuff': 4, 'opponent_status': 996, 'user_boost': 54},
                'total_uses': 28345},
  'bodyslam': { 'effects': {'damage': 32088, 'opponent_debuff': 19, 'opponent_status': 1893, 'user_boost': 140},
                'total_uses': 62268},
  'clamp': { 'effects': {'damage': 3133, 'opponent_debuff': 1, 'opponent_status': 2, 'user_boost': 6},
             'total_uses': 6089},
  'confuseray': {'effects': {'damage': 437, 'opponent_status': 1, 'user_boost': 8}, 'total_uses': 1633},
  'counter': { 'effects': {'damage': 742, 'opponent_debuff': 1, 'opponent_status': 2, 'user_boost': 6},
               'total_uses': 2851},
  'doubleedge': {'effects': {'damage': 1210, 'user_boost': 4}, 'total_uses': 2713},
  'doublekick': {'effects': {'damage': 639, 'user_boost': 2}, 'total_uses': 1284},
  'drillpeck': { 'effects': {'damage': 2526, 'opponent_debuff': 1, 'opponent_status': 1, 'user_boost': 5},
                 'total_uses': 5542},
  'earthquake': { 'effects': {'damage': 7081, 'opponent_debuff': 3, 'opponent_status': 10, 'user_boost': 40},
                  'total_uses': 15694},
  'explosion': {'effects': {'damage': 2636, 'opponent_debuff': 1, 'user_boost': 1}, 'total_uses': 4656},
  'fireblast': {'effects': {'damage': 476, 'opponent_status': 127, 'user_boost': 2}, 'total_uses': 938},
  'firespin': {'effects': {'damage': 33}, 'total_uses': 62},
  'hyperbeam': { 'effects': {'damage': 4381, 'opponent_debuff': 1, 'opponent_status': 3, 'user_boost': 21},
                 'total_uses': 15250},
  'hypnosis': {'effects': {'damage': 65, 'opponent_status': 956, 'user_boost': 7}, 'total_uses': 2991},
  'icebeam': { 'effects': {'damage': 11850, 'opponent_debuff': 2, 'opponent_status': 1066, 'user_boost': 65},
               'total_uses': 23086},
  'lovelykiss': {'effects': {'damage': 135, 'opponent_status': 1715, 'user_boost': 8}, 'total_uses': 4514},
  'megadrain': {'effects': {'damage': 849, 'healing': 1040, 'opponent_status': 1, 'user_boost': 4}, 'total_uses': 2140},
  'nightshade': {'effects': {'damage': 1041, 'opponent_debuff': 1, 'user_boost': 4}, 'total_uses': 2286},
  'psychic': { 'effects': {'damage': 22178, 'opponent_debuff': 7000, 'opponent_status': 9, 'user_boost': 141},
               'total_uses': 47964},
  'razorleaf': {'effects': {'damage': 263, 'user_boost': 1}, 'total_uses': 689},
  'recover': { 'effects': { 'damage': 392,
                            'healing': 6662,
                            'opponent_debuff': 2,
                            'opponent_status': 1,
                            'user_boost': 39},
               'total_uses': 9344},
  'reflect': { 'effects': {'damage': 274, 'opponent_debuff': 1, 'opponent_status': 4, 'user_boost': 5586},
               'total_uses': 7808},
  'rest': { 'effects': {'damage': 247, 'healing': 4201, 'opponent_status': 2, 'user_boost': 13, 'user_status': 4317},
            'total_uses': 11487},
  'rockslide': {'effects': {'damage': 687, 'opponent_status': 2, 'user_boost': 3}, 'total_uses': 1993},
  'seismictoss': {'effects': {'damage': 10132, 'opponent_status': 1, 'user_boost': 27}, 'total_uses': 17921},
  'selfdestruct': {'effects': {'damage': 1413, 'opponent_debuff': 2, 'user_boost': 6}, 'total_uses': 2437},
  'sing': {'effects': {'damage': 116, 'opponent_status': 1145, 'user_boost': 12}, 'total_uses': 3944},
  'slash': {'effects': {'damage': 626, 'user_boost': 2}, 'total_uses': 1179},
  'sleeppowder': { 'effects': {'damage': 333, 'opponent_debuff': 3, 'opponent_status': 4778, 'user_boost': 16},
                   'total_uses': 13420},
  'softboiled': { 'effects': {'damage': 511, 'healing': 10541, 'opponent_status': 1, 'user_boost': 65},
                  'total_uses': 14282},
  'stunspore': {'effects': {'damage': 122, 'opponent_status': 1179, 'user_boost': 7}, 'total_uses': 3840},
  'substitute': {'effects': {'damage': 28, 'user_boost': 1124}, 'total_uses': 1823},
  'surf': {'effects': {'damage': 2298, 'opponent_debuff': 2, 'user_boost': 17}, 'total_uses': 4913},
  'swordsdance': {'effects': {'damage': 7, 'user_boost': 333}, 'total_uses': 355},
  'thunderbolt': { 'effects': {'damage': 11201, 'opponent_debuff': 3, 'opponent_status': 338, 'user_boost': 130},
                   'total_uses': 23211},
  'thunderwave': { 'effects': {'damage': 1077, 'opponent_debuff': 9, 'opponent_status': 15395, 'user_boost': 105},
                   'total_uses': 30486},
  'toxic': {'effects': {'damage': 246, 'opponent_status': 330, 'user_boost': 1}, 'total_uses': 766},
  'wrap': {'effects': {'damage': 2117, 'user_boost': 2}, 'total_uses': 3566}}
